# Chroma向量数据库配置

# 集合名称
collection_name: "algomate"

# 持久化目录
persist_directory: "./data/chromd_db"

# MD5记录文件路径（用于去重）
md5_hex_store: "./data/md5.text"

# 知识库数据目录
data_path: "./data/knowledge_base"

# 允许的文件类型
allow_knowledge_file_type: [".txt", ".pdf"]
